apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakF4TVRNeApOakUwTURGYUZ3MDBNakF4TVRNeE5qRTBNREZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDL2dSTm1zN1E5ZU9FcU54UW4yWVcyTmR2eVFNT1BjbUgrRFBrdVlhYm9uMjYzWU1GSgp4V0drYXdRejJlakVtV05ybGZxVGVCV2pNUzUrbXdWM0tNQ2JtZ1JQMHFZMjlhL3ZtbHI1bnJTYkNsUkpPVnYvCnNlMktRRm1udStKVWEyc1A4SzVCSURCWjRDdUo0QkQ3djZmMHhhbHduTisrT0QzUk45aVlYZGFvNGQvZGxvUDgKS2lGSjY1dWJuTVJuRmtqMldSL3hmOEJMOXI4cnpBY2NYM1BLeTZTaHlnMFlOUWJ0THcySXJHVG1zUStOMHMvWApyb3lZQjRFN2ZOMGphbVUvTEFhWFg5WHUreG1xYk5YNEMwWU9zZFc1WDcxOU56WXAzTTZVR2w0TTBLQjk0cjJRCjRWRU5KZ3VhbTJ0NHlJK3N2V3ZMTTIxYnRZajR5MW03bERSbEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlMyTDZiT2k5bHdyazlpMzR6YgpSLzJmeEJoMUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFsblBTL1NQZ1phQUdrQ3dkWGt0ZSttWGNuYXBRCnVyc2FGRnJyUW40czMwVTN5N3VDQnJWZTR5UVgyYnUyME5QQmMwREdmQXhlOHFYZHVFeE41Vy9BYXVyZHJxSXcKeGo1UVA1WWs0Nnd5c2pzaDB3dW8rR0FOMlU1NnVoekNSTlpmdFVCblJNUkxtdWExTUIzZG5wMVZNSnJSaVhoZwpoTkhlSisveUNMUCs2TTNYTDZJLyt5YVhWa1VsbGYyYUZvc1hna1Zpd2ZrM0hWSWY2M0pKQ0FGYWxoN2J5Z1dJCkRDNFVxN2puQ2FIUmUzRGhhblAvbFhVWTQ5anhlNHJtUG0xRFlUQzErZDk1T0FKNkFsekRTN3ZRZ1FwNXhtNTkKVUpobGp6bmRRbDk4aXVNTDEwZHg2N1U3V1gyZ3F1REh6Vkd2SjBtN1VHNlFHYXc3cjdVS1cvdFliQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://cd882b4d-836a-4350-93f8-21d45e572a6f.k8s.ondigitalocean.com
  name: do-fra1-k8s-1-21-5-do-0-fra1-1642090395986
contexts:
- context:
    cluster: do-fra1-k8s-1-21-5-do-0-fra1-1642090395986
    user: do-fra1-k8s-1-21-5-do-0-fra1-1642090395986-admin
  name: do-fra1-k8s-1-21-5-do-0-fra1-1642090395986
current-context: do-fra1-k8s-1-21-5-do-0-fra1-1642090395986
kind: Config
preferences: {}
users:
- name: do-fra1-k8s-1-21-5-do-0-fra1-1642090395986-admin
  user:
    token: bb80d0c7bdc3ea0760be7fd6e3c0723fcee04545fe3cf79c6c9b9324bcecc50d
