apiVersion: v1
kind: Service
metadata:
  name: dataload-svc
  labels:
    app: dataload
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: dataload
