apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataload-dep
  labels:
    app: dataload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dataload
  template:
    metadata:
      labels:
        app: dataload
    spec:
      containers:
      - name: dataload
        image: cmauri75/dataload:latest
        ports:
        - containerPort: 8080
